# Generated by Django 4.2.2 on 2023-06-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('stdname', models.CharField(default='', max_length=55)),
                ('stdemail', models.CharField(default='', max_length=100)),
                ('stdadd', models.CharField(default='', max_length=255)),
                ('stdphone', models.CharField(default='', max_length=10)),
                ('stdbranch', models.CharField(default='', max_length=55)),
                ('stdgender', models.CharField(default='', max_length=6)),
            ],
        ),
    ]
