# Generated by Django 4.2.2 on 2023-06-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stdbranch',
            new_name='stdfaculty',
        ),
    ]
