# Generated by Django 4.2.2 on 2023-06-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_rename_stdbranch_student_stdfaculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stdimage',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
