# Generated by Django 4.2.2 on 2023-06-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_student_stdimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stdimage',
            field=models.ImageField(default='', upload_to='stdimg'),
        ),
    ]
