# Generated by Django 4.2.2 on 2023-06-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_alter_student_stdimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('stf_id', models.AutoField(primary_key=True, serialize=False)),
                ('stfname', models.CharField(default='', max_length=55)),
                ('stfemail', models.CharField(default='', max_length=100)),
                ('stfadd', models.CharField(default='', max_length=255)),
                ('stfphone', models.CharField(default='', max_length=10)),
                ('stfrole', models.CharField(default='', max_length=55)),
                ('stfgender', models.CharField(default='', max_length=6)),
                ('stfimage', models.ImageField(default='', upload_to='stdimg')),
            ],
        ),
    ]
