# Generated by Django 4.2.2 on 2023-06-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=55)),
                ('email', models.EmailField(default='', max_length=55)),
                ('comment', models.TextField(default='')),
            ],
        ),
    ]
