# Generated by Django 4.2.2 on 2023-06-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visualize',
            fields=[
                ('snum', models.AutoField(primary_key=True, serialize=False)),
                ('datas', models.CharField(default='', max_length=100)),
                ('names', models.CharField(default='', max_length=255)),
                ('graph', models.ImageField(default='', upload_to='graphs/')),
            ],
        ),
    ]
