# Generated by Django 4.2.2 on 2023-06-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visualize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualize',
            name='fname',
            field=models.CharField(default='', max_length=55),
        ),
    ]
