# Generated by Django 4.2.2 on 2023-06-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visualize', '0002_visualize_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualize',
            name='graph',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
