# Generated by Django 4.2.2 on 2023-06-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visualize', '0003_alter_visualize_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualize',
            name='file',
            field=models.FileField(default='', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='graph',
            field=models.ImageField(default='', upload_to='graphs'),
        ),
    ]
