# Generated by Django 5.0.1 on 2024-01-21 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visualize', '0004_visualize_file_alter_visualize_graph'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualize',
            name='file',
        ),
        migrations.AddField(
            model_name='visualize',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FileVisualize',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(default='', upload_to='files')),
                ('graph', models.ImageField(default='', upload_to='file/graphs')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
