# Generated by Django 5.0.1 on 2024-01-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visualize', '0005_remove_visualize_file_visualize_user_filevisualize'),
    ]

    operations = [
        migrations.AddField(
            model_name='filevisualize',
            name='plottype',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='filevisualize',
            name='xlabelfile',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='filevisualize',
            name='ylabelfile',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
